apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-ui-config
  labels:
    app.kubernetes.io/name: guestbook-ui
    app.kubernetes.io/part-of: gitops-demo
data:
  UI_PROPERTIES_FILE_NAME: "guestbook-ui.properties"
  ENVIRONMENT: "demo"
